# Generated by Django 4.2.4 on 2023-08-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_button1", models.CharField(max_length=50)),
                ("selected_button2", models.CharField(max_length=50)),
                ("selected_button3", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
