# Generated by Django 4.2.4 on 2023-08-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_quizresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="recommendedGender",
            field=models.CharField(default="male", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="recommendedSkinColor",
            field=models.CharField(default="brown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="recommendedWearingArea",
            field=models.CharField(default="outdoor", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quizresponse",
            name="selected_button1",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="quizresponse",
            name="selected_button2",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="quizresponse",
            name="selected_button3",
            field=models.CharField(max_length=100),
        ),
    ]
