# Generated by Django 4.2.4 on 2023-08-25 01:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_favoriteitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favoriteitem",
            name="product",
        ),
        migrations.AddField(
            model_name="favoriteitem",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.category",
            ),
        ),
        migrations.AddField(
            model_name="favoriteitem",
            name="description",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="favoriteitem",
            name="image",
            field=models.ImageField(default="image.png", upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="favoriteitem",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="favoriteitem",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
